POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFiZWwiLCJpZCI6IjY4MWUwNjE5Y2MxMjQ0NTVkY2M5NzVjYyIsImlhdCI6MTc0NjgwMzU2OH0.uSMQJVNxLBGaBbFQ_VMtFZtpFndrhlSEcmkXpUe9ecE

{
    "title": "Code Works 101",
    "author": "Julius",
    "url": "https//:Helo",
    "likes": 644
}